-- flag_suspicious.sql
--
-- This is a MACRO file. Macros are reusable Jinja functions that you can
-- call from any model. They live in the macros/ folder.
--
-- Your job: create a macro called "flag_suspicious" that takes a column name
-- for the result and returns a CASE WHEN expression that flags suspicious
-- shipments.
--
-- A shipment is suspicious if ANY of these are true:
--   - voss_flag = 1
--   - dest_is_federation = false
--   - cargo_type = 'classified'
--
-- Macro syntax:
--   {% macro macro_name(parameter) %}
--     ... SQL that gets inserted where the macro is called ...
--   {% endmacro %}
--
-- Then in a model you call it with: {{ macro_name('column_name') }}
--
-- Check the objectives panel for specifics.
